---
title: "Reporte de Reproducibilidad"
subtitle: "Artículo: II Encuesta Nacional sobre Uso del Tiempo (ENUT 2023) <br><a href='https://github.com/josefinabd/ej-repro-grupo3' target='_blank' ><i class='bi bi-github'></i></a>" # reemplazar con dirección al repositorio del proyecto
author:
  - name: Josefina Bustos
    email: josefina.bustos.d@ug.uchile.cl 
    affiliations:
      - ref: 1
  - name: Benjamin Casacuberta
    email: b.casacuberta@ug.uchile.cl
    affiliations:
      - ref: 1
affiliations: 
  - id: 1
    name: Departamento de Sociología, Universidad de Chile
date: "05-04-2026"
lang: "es"
fontsize: 13pt
format:
  html:
    code-fold: true
    code-summary: "Show the code"
    toc: true
    toc-location: right
    toc-depth: 2
    toc-expand: 2
    toc-title: Contenidos
    number-sections: true
    number-depth: 3
    theme:
        - libs/ocs.scss
    code-link: true
    title-block-banner: true
    include-in-header:
      text: |
        <style>
          h1.title {
            color: #ffffff !important;
          }
          .subtitle {
            color: #ffffff !important;
          }
        </style>
  pdf:
    toc: true
    number-sections: true
    geometry: margin=2.5cm
editor_options: 
  chunk_output_type: console
bibliography: "input/bib/bibliog_enut.bib"
csl: "input/bib/apa7.csl"
---

# Selección de artículo
El artículo seleccionado para el análisis de reproducibilidad es la segunda Encuesta Nacional sobre Uso de Tiempo (ENUT), publicada por el Instituto Nacional de Estadística en Chile. Esta encuesta permite conocer cómo las personas distribuyen su tiempo entre diferentes actividades, como trabajo, estudio, ocio, entre otras. 

El objetivo general de la encuesta es "obtener información de cómo las personas de 12 años o más utilizan su tiempo, principalmente en torno al trabajo no remunerado, trabajo en la ocupación y actividades personales; además de proveer información relacionada a su calidad de vida y bienestar respecto a su uso de tiempo en las principales zonas urbanas del país" [@ineficha2025].

Entre los objetivos específicos se encuentra: identificar brechas de género, medición de carga laboral a través del tiempo dedicado a la ocupación y trabajo no remunerado, medir uso de tiempo y satisfacción de la población, y por último, identificar acceso y necesidad de servicios e instituciones de cuidado para la población dependiente. 

Para el reporte de reproducibilidad, se escoge este artículo con el propósito de tener una base de datos amplia y detallada sobre el uso del tiempo en la población chilena, lo que nos permitirá realizar un análisis reproducible significativo y relevante. Además, la encuesta proporciona una gran cantidad de variables y resultados que pueden ser utilizados para explorar diferentes aspectos del uso del tiempo (como los presentados en los objetivos de la encuesta) lo que nos permitirá profundizar en el análisis y obtener insights valiosos sobre las actividades diarias de las personas.

En ese sentido, desde el informe de principales resultados de la encuesta, hemos escogido la tabla 16 que muestra la participación y tiempo destinado al trabajo no remunerado según sexo y nacionalidad. 


# Evaluación de reproducibilidad

  -   **Disponibilidad de datos**: 
  El artículo sí proporciona acceso a los datos utilizados en el estudio. Los datos están disponibles a través del sitio web del Instituto Nacional de Estadística de Chile, donde se pueden descargar en variados formatos. No hubo dificultades para obtener los datos, ya que el acceso es público y se encuentra claramente indicado en la página web. Además, el artículo incluye un enlace directo a la sección de descarga de datos.   
  -   **Disponibilidad de código**: 
  No obstante, el artículo no proporciona acceso al código para el análisis. Sin embargo, en el *Manual de Uso de base de datos* se describen las variables y se entrega de manera robusta el flujo de trabajo que se llevó a cabo para procesar correctamente los microdatos de la encuesta, lo que puede ser de gran ayuda para la replicabilidad. En ese sentido, se especifica la organización de la estructura de la base de datos; librerías necesarias para el procesamiento y la limpieza; metodología para la construcción de indicadores complejos a partir de las preguntas base del cuestionario y, por último, el diseño muestral complejo para asegurar resultados representativos. A pesar de esto, la falta de acceso al código específico utilizado en el estudio dificulta la replicación exacta del análisis realizado, por lo que se utilizarán códigos propios para el proceso de reproducción.  
  -   **Documentación**: ¿El artículo incluye una descripción clara de los métodos y procedimientos utilizados en el estudio? ¿Es suficiente para que otro investigador pueda replicar el estudio?
  -   **Transparencia**: ¿El artículo proporciona información sobre los posibles conflictos de interés, financiamiento, y otros aspectos relacionados con la transparencia de la investigación?   

# Análisis reproducible
Seleccionar un resultado específico del artículo (por ejemplo, una tabla de resultados o una figura) y tratar de reproducirlo utilizando los datos y el código proporcionados. Documentar el proceso de reproducción, incluyendo cualquier dificultad encontrada y cómo se resolvió.

## Resultado a reproducir
- Imagen de tabla(s), figura(s) o resultado específico del artículo seleccionado, junto a una breve descripción.

## Proceso de reproducción

- Descripción detallada del proceso seguido para reproducir el resultado seleccionado, incluyendo los pasos realizados, las herramientas utilizadas, y cualquier ajuste necesario para lograr la reproducción. Incluye las siguientes sub secciones:

### Procesamiento

- Incluye el código utilizado para procesar los datos, junto con una explicación de cada paso. 

- Los datos originales deben ser llamados desde input/data/original, el código de procesamiento se debe incluir en este mismo archivo (reporte-repro.qmd).

### Reproducción

- Generación de tabla o figura a reproducir.

# Conclusiones

Basándose en el análisis realizado, escriban una conclusión sobre el nivel de reproducibilidad del artículo seleccionado.

# Recomendaciones

Recomendaciones para mejorar la reproducibilidad del artículo, si es necesario.

# Referencias

::: {#refs}
:::

# Apéndice

## Material suplementario

- Incluyan aquí detalles metodológicos adicionales, en caso de ser necesario

## Código

- Incluir acá el código original, en caso de estar disponible.


